taskname: '+ MobileViTv1-Small DeepLabv3'
common:
  run_label: "train"
  accum_freq: 2
  log_freq: 200
  auto_resume: true
  mixed_precision: true
dataset:
  root_train: "/root/workspace/nmode_cifar10/ml-cvnets/Dataset/VOCdevkit/"
  root_val: "/root/workspace/nmode_cifar10/ml-cvnets/Dataset/VOCdevkit/"
  name: "pascal"
  category: "segmentation"
  train_batch_size0: 8 # effective batch size is 128 (32 * 4 GPUs)
  val_batch_size0: 8
  eval_batch_size0: 1
  workers: 8
  persistent_workers: false
  pin_memory: false
  pascal:
    use_coco_data: False
    coco_root_dir: "/mnt/vision_datasets/coco_preprocess"
image_augmentation:
  random_crop:
    enable: true
    seg_class_max_ratio: 0.75
    pad_if_needed: true
    mask_fill: 255 # background idx is 255
  random_horizontal_flip:
    enable: true
  resize:
    enable: true
    size: [256, 256]
    interpolation: "bilinear"
  random_short_size_resize:
    enable: true
    interpolation: "bilinear"
    short_side_min: 256
    short_side_max: 768
    max_img_dim: 1024
  photo_metric_distort:
    enable: true
  random_rotate:
    enable: true
    angle: 10
    mask_fill: 255 # background idx is 255
  random_gaussian_noise:
    enable: true
sampler:
  name: "batch_sampler"
  bs:
    crop_size_width: 256
    crop_size_height: 256
loss:
  category: "segmentation"
  segmentation:
    name: "cross_entropy"
    cross_entropy:
      ignore_index: 255
optim:
  name: "adamw"
  weight_decay: 0.01
  no_decay_bn_filter_bias: false
  adamw:
    beta1: 0.9
    beta2: 0.999
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 50
  warmup_iterations: 500
  warmup_init_lr: 0.00009
  cosine:
    max_lr: 0.0009
    min_lr: 1.e-6
model:
  segmentation:
    name: "encoder_decoder"
    n_classes: 21
    lr_multiplier: 10
    seg_head: "deeplabv3"
    output_stride: 8
    classifier_dropout: 0.1
    use_aux_head: true
    activation:
      name: "relu"
    deeplabv3:
      aspp_dropout: 0.1
      aspp_sep_conv: false
      aspp_out_channels: 512
      aspp_rates: [ 12, 24, 36 ]
  classification:
    name: "mobilenetv1_ode"
    mitv2:
      width_multiplier: 2.0
      attn_norm_layer: "layer_norm_2d"
    activation:
      name: "swish"
  normalization:
    name: "sync_batch_norm"
    momentum: 0.1
  activation:
    name: "relu"
    inplace: false
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "normal"
ema:
  enable: true
  momentum: 0.0005
stats:
  val: [ "loss", "iou" ]
  train: [ "loss" ]
  checkpoint_metric: "iou"
  checkpoint_metric_max: true
